#cloud-config

bootcmd:
  - mkdir -p /etc/ecs
  - echo 'ECS_CLUSTER=${ecs_cluster_name}' >> /etc/ecs/ecs.config
%{ if length(efs_mounts_hosts_entries) > 0 ~}
%{ for efs_mount_dns, efs_mount_ip in efs_mounts_hosts_entries ~}
  - echo '${efs_mount_ip} ${efs_mount_dns}' >> /etc/ecs/ecs.config
%{ endfor ~}
  - yum install -y amazon-efs-utils
%{ endif ~}